### ISSUE TITLE
[1pt] Group Task #0 - Setup Kanban Board

### ISSUE THREAD

**Issue by JuanDiegoGuerra** [cancelei/EsportGamingCenter_backend#18]
- In this milestone we have setted up the Kanban Board and assigned all the task to the respective team member.
- Project : [Kanban Board](https://github.com/users/cancelei/projects/7)
> Group of 5: ( @JuanDiegoGuerra @alvp01 @cancelei @Gardimy @lerfast ) 👨🏼‍🚀
![image](https://github.com/cancelei/EsportGamingCenter_backend/assets/45726631/17119158-dc80-416e-a44a-8fc5b4b205c3)

**Comment by Meltrust** [comment]
Hi,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- ✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️
- [ ] Please, add a description to this task:

![image](https://github.com/cancelei/EsportGamingCenter_backend/assets/57421823/39fb8c90-6aa3-4cc2-8865-9e3629ee20d1)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by JuanDiegoGuerra** [comment]
###  Required changes made 🛠
- **Fixed:** _"Please, add a description to this task: [External API connection](https://github.com/cancelei/EsportGamingCenter_backend/issues/17) "_ 🛠

![todolist1](https://user-images.githubusercontent.com/45726631/231703283-083f07c2-f037-4fa4-a834-be7d3bd26e06.gif)

**Comment by Meltrust** [comment]
## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All tasks have descriptions now✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
